In [262]:
pip install alpha-vantage

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: alpha-vantage in /usr/local/lib/python3.10/dist-packages (2.3.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from alpha-vantage) (3.8.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from alpha-vantage) (2.27.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->alpha-vantage) (1.3.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->alpha-vantage) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->alpha-vantage) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->alpha-vantage) (3.4)

In [263]:
from alpha_vantage.timeseries import TimeSeries
import pandas as pd
import requests

In [264]:
class ScriptData:
    def __init__(self, api_key):
        self.api_key = api_key
        self.data = {}

    def fetch_intraday_data(self, script):
        url = f"https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol={script}&interval=1min&apikey={self.api_key}"
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            if "Time Series (1min)" in data:
                self.data[script] = data["Time Series (1min)"]
                print(self.data[script])
            else:
                print("No intraday data available for the given script.")
        else:
            print("Failed to fetch intraday data.")

    def convert_intraday_data(self, script):
        if script in self.data:
            intraday_data = self.data[script]
            df = pd.DataFrame.from_dict(intraday_data, orient='index')
            df.columns = ['open', 'high', 'low', 'close', 'volume']
            df.index = pd.to_datetime(df.index)
            df['timestamp'] = df.index
            df['open'] = df['open'].astype(float)
            df['high'] = df['high'].astype(float)
            df['low'] = df['low'].astype(float)
            df['close'] = df['close'].astype(float)
            df['volume'] = df['volume'].astype(int)
            df.reset_index(inplace = True, drop = True)
            return df
        else:
            print("No intraday data available for the given script.")

    def __getitem__(self, key):
        return self.data[key]

    def __setitem__(self, key, value):
        self.data[key] = value

    def __contains__(self, key):
        return key in self.data

def indicator1(df, timeperiod):
    df['indicator'] = df['close'].rolling(window=timeperiod, min_periods=1).mean()
    result_df = df[['timestamp', 'indicator']].copy()
    return result_df

In [265]:
script_data = ScriptData('NGH809FJTDN47GSX')
script_data.fetch_intraday_data('GOOGL')
script_data.convert_intraday_data('GOOGL')

{'2023-06-12 19:58:00': {'1. open': '123.8300', '2. high': '123.8300', '3. low': '123.8300', '4. close': '123.8300', '5. volume': '434'}, '2023-06-12 19:57:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '663'}, '2023-06-12 19:56:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '439'}, '2023-06-12 19:55:00': {'1. open': '123.8400', '2. high': '123.8400', '3. low': '123.8400', '4. close': '123.8400', '5. volume': '130'}, '2023-06-12 19:54:00': {'1. open': '123.8800', '2. high': '123.8800', '3. low': '123.8800', '4. close': '123.8800', '5. volume': '335'}, '2023-06-12 19:53:00': {'1. open': '123.8200', '2. high': '123.8200', '3. low': '123.8200', '4. close': '123.8200', '5. volume': '464'}, '2023-06-12 19:52:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '226'}, '2023-06-12 19:50:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '627'}, '2023-06-12 19:49:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '110'}, '2023-06-12 19:47:00': {'1. open': '123.9200', '2. high': '123.9200', '3. low': '123.9200', '4. close': '123.9200', '5. volume': '1348'}, '2023-06-12 19:46:00': {'1. open': '123.9200', '2. high': '123.9200', '3. low': '123.9200', '4. close': '123.9200', '5. volume': '635'}, '2023-06-12 19:44:00': {'1. open': '123.9500', '2. high': '123.9500', '3. low': '123.9500', '4. close': '123.9500', '5. volume': '1002'}, '2023-06-12 19:43:00': {'1. open': '123.9500', '2. high': '123.9500', '3. low': '123.9500', '4. close': '123.9500', '5. volume': '525'}, '2023-06-12 19:40:00': {'1. open': '123.9101', '2. high': '123.9101', '3. low': '123.9101', '4. close': '123.9101', '5. volume': '138'}, '2023-06-12 19:39:00': {'1. open': '123.9400', '2. high': '123.9400', '3. low': '123.9400', '4. close': '123.9400', '5. volume': '152'}, '2023-06-12 19:38:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '862'}, '2023-06-12 19:36:00': {'1. open': '123.9700', '2. high': '123.9700', '3. low': '123.9700', '4. close': '123.9700', '5. volume': '1367'}, '2023-06-12 19:35:00': {'1. open': '123.9700', '2. high': '123.9700', '3. low': '123.9700', '4. close': '123.9700', '5. volume': '1056'}, '2023-06-12 19:34:00': {'1. open': '123.9500', '2. high': '123.9800', '3. low': '123.9500', '4. close': '123.9800', '5. volume': '1696'}, '2023-06-12 19:33:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '1799'}, '2023-06-12 19:28:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '149'}, '2023-06-12 19:27:00': {'1. open': '123.7700', '2. high': '123.7700', '3. low': '123.7600', '4. close': '123.7600', '5. volume': '431'}, '2023-06-12 19:17:00': {'1. open': '123.9400', '2. high': '123.9400', '3. low': '123.9400', '4. close': '123.9400', '5. volume': '532'}, '2023-06-12 19:13:00': {'1. open': '123.8000', '2. high': '123.8000', '3. low': '123.8000', '4. close': '123.8000', '5. volume': '348'}, '2023-06-12 19:03:00': {'1. open': '123.8800', '2. high': '123.8800', '3. low': '123.8800', '4. close': '123.8800', '5. volume': '222'}, '2023-06-12 19:01:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '107'}, '2023-06-12 19:00:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '276'}, '2023-06-12 18:59:00': {'1. open': '123.9400', '2. high': '123.9400', '3. low': '123.9400', '4. close': '123.9400', '5. volume': '148'}, '2023-06-12 18:56:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '190'}, '2023-06-12 18:53:00': {'1. open': '123.8000', '2. high': '123.8000', '3. low': '123.8000', '4. close': '123.8000', '5. volume': '560'}, '2023-06-12 18:49:00': {'1. open': '123.8000', '2. high': '123.8000', '3. low': '123.8000', '4. close': '123.8000', '5. volume': '1003'}, '2023-06-12 18:48:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '1245'}, '2023-06-12 18:46:00': {'1. open': '123.8000', '2. high': '123.8500', '3. low': '123.8000', '4. close': '123.8500', '5. volume': '2633'}, '2023-06-12 18:45:00': {'1. open': '123.8200', '2. high': '123.8200', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '538'}, '2023-06-12 18:44:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '525'}, '2023-06-12 18:43:00': {'1. open': '123.7900', '2. high': '123.8000', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '1528'}, '2023-06-12 18:33:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '375'}, '2023-06-12 18:32:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '255'}, '2023-06-12 18:30:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '299'}, '2023-06-12 18:28:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7400', '4. close': '123.7500', '5. volume': '504'}, '2023-06-12 18:25:00': {'1. open': '123.8104', '2. high': '123.8104', '3. low': '123.8104', '4. close': '123.8104', '5. volume': '193'}, '2023-06-12 18:24:00': {'1. open': '123.8300', '2. high': '123.8300', '3. low': '123.8300', '4. close': '123.8300', '5. volume': '209'}, '2023-06-12 18:22:00': {'1. open': '123.7412', '2. high': '123.7412', '3. low': '123.7400', '4. close': '123.7400', '5. volume': '515'}, '2023-06-12 18:18:00': {'1. open': '123.7425', '2. high': '123.7425', '3. low': '123.7425', '4. close': '123.7425', '5. volume': '132'}, '2023-06-12 18:16:00': {'1. open': '123.7424', '2. high': '123.7424', '3. low': '123.7424', '4. close': '123.7424', '5. volume': '262'}, '2023-06-12 18:14:00': {'1. open': '123.8153', '2. high': '123.8200', '3. low': '123.8153', '4. close': '123.8200', '5. volume': '413'}, '2023-06-12 18:13:00': {'1. open': '123.7300', '2. high': '123.7400', '3. low': '123.7300', '4. close': '123.7400', '5. volume': '410'}, '2023-06-12 18:12:00': {'1. open': '123.7300', '2. high': '123.7300', '3. low': '123.7300', '4. close': '123.7300', '5. volume': '296'}, '2023-06-12 18:08:00': {'1. open': '123.6360', '2. high': '123.7398', '3. low': '123.6360', '4. close': '123.7398', '5. volume': '1368'}, '2023-06-12 18:06:00': {'1. open': '123.7388', '2. high': '123.7388', '3. low': '123.7388', '4. close': '123.7388', '5. volume': '138'}, '2023-06-12 18:05:00': {'1. open': '123.6700', '2. high': '123.6700', '3. low': '123.6700', '4. close': '123.6700', '5. volume': '437'}, '2023-06-12 18:01:00': {'1. open': '123.7000', '2. high': '123.7399', '3. low': '123.7000', '4. close': '123.7399', '5. volume': '750'}, '2023-06-12 17:56:00': {'1. open': '123.7000', '2. high': '123.7000', '3. low': '123.7000', '4. close': '123.7000', '5. volume': '526'}, '2023-06-12 17:55:00': {'1. open': '123.6900', '2. high': '123.6900', '3. low': '123.6900', '4. close': '123.6900', '5. volume': '156'}, '2023-06-12 17:54:00': {'1. open': '123.7000', '2. high': '123.7000', '3. low': '123.7000', '4. close': '123.7000', '5. volume': '154'}, '2023-06-12 17:52:00': {'1. open': '123.6571', '2. high': '123.6571', '3. low': '123.6571', '4. close': '123.6571', '5. volume': '283'}, '2023-06-12 17:49:00': {'1. open': '123.6700', '2. high': '123.7400', '3. low': '123.6700', '4. close': '123.7400', '5. volume': '875'}, '2023-06-12 17:47:00': {'1. open': '123.6400', '2. high': '123.6400', '3. low': '123.6400', '4. close': '123.6400', '5. volume': '263'}, '2023-06-12 17:46:00': {'1. open': '123.6400', '2. high': '123.6400', '3. low': '123.6400', '4. close': '123.6400', '5. volume': '218'}, '2023-06-12 17:44:00': {'1. open': '123.6100', '2. high': '123.6200', '3. low': '123.6100', '4. close': '123.6200', '5. volume': '282'}, '2023-06-12 17:43:00': {'1. open': '123.6102', '2. high': '123.6102', '3. low': '123.6100', '4. close': '123.6100', '5. volume': '745'}, '2023-06-12 17:41:00': {'1. open': '123.6500', '2. high': '123.6500', '3. low': '123.6500', '4. close': '123.6500', '5. volume': '1010'}, '2023-06-12 17:40:00': {'1. open': '123.6200', '2. high': '123.6200', '3. low': '123.6200', '4. close': '123.6200', '5. volume': '368'}, '2023-06-12 17:39:00': {'1. open': '123.8400', '2. high': '123.8400', '3. low': '123.8400', '4. close': '123.8400', '5. volume': '845'}, '2023-06-12 17:38:00': {'1. open': '123.6200', '2. high': '123.6700', '3. low': '123.6000', '4. close': '123.6000', '5. volume': '789'}, '2023-06-12 17:37:00': {'1. open': '123.7900', '2. high': '123.8400', '3. low': '123.6400', '4. close': '123.6400', '5. volume': '5393'}, '2023-06-12 17:36:00': {'1. open': '123.7899', '2. high': '123.7899', '3. low': '123.7700', '4. close': '123.7700', '5. volume': '1201'}, '2023-06-12 17:33:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '105'}, '2023-06-12 17:30:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '1059'}, '2023-06-12 17:23:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '381'}, '2023-06-12 17:17:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '286'}, '2023-06-12 17:15:00': {'1. open': '123.7799', '2. high': '123.7799', '3. low': '123.7799', '4. close': '123.7799', '5. volume': '521'}, '2023-06-12 17:14:00': {'1. open': '123.7100', '2. high': '123.7201', '3. low': '123.7100', '4. close': '123.7201', '5. volume': '564'}, '2023-06-12 17:13:00': {'1. open': '123.7100', '2. high': '123.7100', '3. low': '123.7100', '4. close': '123.7100', '5. volume': '396'}, '2023-06-12 17:12:00': {'1. open': '123.6400', '2. high': '123.7100', '3. low': '123.6400', '4. close': '123.7100', '5. volume': '674476'}, '2023-06-12 17:05:00': {'1. open': '123.7600', '2. high': '123.7600', '3. low': '123.7600', '4. close': '123.7600', '5. volume': '362'}, '2023-06-12 17:04:00': {'1. open': '123.7600', '2. high': '123.7600', '3. low': '123.7600', '4. close': '123.7600', '5. volume': '551'}, '2023-06-12 16:59:00': {'1. open': '123.7400', '2. high': '123.7900', '3. low': '123.7400', '4. close': '123.7800', '5. volume': '1051'}, '2023-06-12 16:58:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '1416'}, '2023-06-12 16:57:00': {'1. open': '123.8200', '2. high': '123.8200', '3. low': '123.8100', '4. close': '123.8100', '5. volume': '439'}, '2023-06-12 16:55:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '237'}, '2023-06-12 16:54:00': {'1. open': '123.7901', '2. high': '123.7901', '3. low': '123.7901', '4. close': '123.7901', '5. volume': '548'}, '2023-06-12 16:53:00': {'1. open': '123.8400', '2. high': '123.8400', '3. low': '123.8400', '4. close': '123.8400', '5. volume': '320'}, '2023-06-12 16:52:00': {'1. open': '123.8500', '2. high': '123.8600', '3. low': '123.8300', '4. close': '123.8300', '5. volume': '3051'}, '2023-06-12 16:51:00': {'1. open': '123.8793', '2. high': '123.8900', '3. low': '123.8501', '4. close': '123.8501', '5. volume': '156990'}, '2023-06-12 16:50:00': {'1. open': '123.8800', '2. high': '123.8800', '3. low': '123.8800', '4. close': '123.8800', '5. volume': '1166'}, '2023-06-12 16:48:00': {'1. open': '123.7900', '2. high': '123.9000', '3. low': '123.7900', '4. close': '123.8900', '5. volume': '6984'}, '2023-06-12 16:45:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.6400', '4. close': '123.7900', '5. volume': '3105'}, '2023-06-12 16:44:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '118'}, '2023-06-12 16:42:00': {'1. open': '123.7300', '2. high': '123.7300', '3. low': '123.7300', '4. close': '123.7300', '5. volume': '881'}, '2023-06-12 16:40:00': {'1. open': '123.7100', '2. high': '123.7200', '3. low': '123.7000', '4. close': '123.7200', '5. volume': '5309'}, '2023-06-12 16:39:00': {'1. open': '123.7000', '2. high': '123.7100', '3. low': '123.7000', '4. close': '123.7100', '5. volume': '508'}, '2023-06-12 16:38:00': {'1. open': '123.6900', '2. high': '123.7000', '3. low': '123.6900', '4. close': '123.7000', '5. volume': '1387'}, '2023-06-12 16:37:00': {'1. open': '123.6900', '2. high': '123.6900', '3. low': '123.6900', '4. close': '123.6900', '5. volume': '951'}, '2023-06-12 16:35:00': {'1. open': '123.6900', '2. high': '123.6900', '3. low': '123.6900', '4. close': '123.6900', '5. volume': '261'}, '2023-06-12 16:34:00': {'1. open': '123.7300', '2. high': '123.7300', '3. low': '123.7300', '4. close': '123.7300', '5. volume': '148'}, '2023-06-12 16:31:00': {'1. open': '123.6848', '2. high': '123.6848', '3. low': '123.6848', '4. close': '123.6848', '5. volume': '594'}, '2023-06-12 16:28:00': {'1. open': '123.7396', '2. high': '123.7400', '3. low': '123.7396', '4. close': '123.7400', '5. volume': '1527'}, '2023-06-12 16:27:00': {'1. open': '123.7067', '2. high': '123.7100', '3. low': '123.7004', '4. close': '123.7004', '5. volume': '591'}, '2023-06-12 16:26:00': {'1. open': '123.7200', '2. high': '123.7200', '3. low': '123.7200', '4. close': '123.7200', '5. volume': '252'}}

        open      high       low     close  volume           timestamp
0   123.8300  123.8300  123.8300  123.8300     434 2023-06-12 19:58:00
1   123.8500  123.8500  123.8500  123.8500     663 2023-06-12 19:57:00
2   123.9000  123.9000  123.9000  123.9000     439 2023-06-12 19:56:00
3   123.8400  123.8400  123.8400  123.8400     130 2023-06-12 19:55:00
4   123.8800  123.8800  123.8800  123.8800     335 2023-06-12 19:54:00
..       ...       ...       ...       ...     ...                 ...
95  123.7300  123.7300  123.7300  123.7300     148 2023-06-12 16:34:00
96  123.6848  123.6848  123.6848  123.6848     594 2023-06-12 16:31:00
97  123.7396  123.7400  123.7396  123.7400    1527 2023-06-12 16:28:00
98  123.7067  123.7100  123.7004  123.7004     591 2023-06-12 16:27:00
99  123.7200  123.7200  123.7200  123.7200     252 2023-06-12 16:26:00

[100 rows x 6 columns]

In [266]:
script_data.fetch_intraday_data('AAPL')
script_data.convert_intraday_data('AAPL')

{'2023-06-12 19:59:00': {'1. open': '182.4600', '2. high': '182.5500', '3. low': '182.4401', '4. close': '182.5099', '5. volume': '9319'}, '2023-06-12 19:58:00': {'1. open': '182.5400', '2. high': '182.5496', '3. low': '182.1000', '4. close': '182.5400', '5. volume': '20613'}, '2023-06-12 19:57:00': {'1. open': '182.5200', '2. high': '182.5900', '3. low': '182.5200', '4. close': '182.5500', '5. volume': '10400'}, '2023-06-12 19:56:00': {'1. open': '182.5000', '2. high': '182.5800', '3. low': '182.4800', '4. close': '182.5800', '5. volume': '6868'}, '2023-06-12 19:55:00': {'1. open': '182.3000', '2. high': '182.7000', '3. low': '182.2000', '4. close': '182.6900', '5. volume': '15533'}, '2023-06-12 19:54:00': {'1. open': '182.2300', '2. high': '182.3500', '3. low': '182.2300', '4. close': '182.3400', '5. volume': '8347'}, '2023-06-12 19:53:00': {'1. open': '181.9000', '2. high': '182.2000', '3. low': '181.8800', '4. close': '182.2000', '5. volume': '8881'}, '2023-06-12 19:52:00': {'1. open': '181.7000', '2. high': '181.8500', '3. low': '181.7000', '4. close': '181.8500', '5. volume': '5727'}, '2023-06-12 19:51:00': {'1. open': '181.7000', '2. high': '181.8000', '3. low': '181.6000', '4. close': '181.8000', '5. volume': '9798'}, '2023-06-12 19:50:00': {'1. open': '181.8000', '2. high': '181.8000', '3. low': '181.7100', '4. close': '181.7100', '5. volume': '5643'}, '2023-06-12 19:49:00': {'1. open': '181.8000', '2. high': '181.8000', '3. low': '181.7800', '4. close': '181.8000', '5. volume': '11513'}, '2023-06-12 19:48:00': {'1. open': '181.8000', '2. high': '181.8000', '3. low': '181.7800', '4. close': '181.8000', '5. volume': '7866'}, '2023-06-12 19:47:00': {'1. open': '181.6900', '2. high': '181.8000', '3. low': '181.6900', '4. close': '181.7900', '5. volume': '4844'}, '2023-06-12 19:46:00': {'1. open': '181.5100', '2. high': '181.7700', '3. low': '181.5000', '4. close': '181.7000', '5. volume': '11705'}, '2023-06-12 19:45:00': {'1. open': '181.8500', '2. high': '181.8800', '3. low': '181.5200', '4. close': '181.6100', '5. volume': '11920'}, '2023-06-12 19:44:00': {'1. open': '181.9000', '2. high': '181.9400', '3. low': '181.6300', '4. close': '181.7700', '5. volume': '6975'}, '2023-06-12 19:43:00': {'1. open': '181.9900', '2. high': '182.0000', '3. low': '181.8100', '4. close': '181.9000', '5. volume': '12070'}, '2023-06-12 19:42:00': {'1. open': '181.9000', '2. high': '182.2500', '3. low': '181.9000', '4. close': '181.9000', '5. volume': '15471'}, '2023-06-12 19:41:00': {'1. open': '181.9000', '2. high': '181.9000', '3. low': '181.8500', '4. close': '181.9000', '5. volume': '6240'}, '2023-06-12 19:40:00': {'1. open': '181.8800', '2. high': '181.9000', '3. low': '181.7500', '4. close': '181.9000', '5. volume': '8018'}, '2023-06-12 19:39:00': {'1. open': '182.0000', '2. high': '182.0000', '3. low': '181.8000', '4. close': '181.9000', '5. volume': '12915'}, '2023-06-12 19:38:00': {'1. open': '182.0000', '2. high': '182.0000', '3. low': '181.9800', '4. close': '182.0000', '5. volume': '5976'}, '2023-06-12 19:37:00': {'1. open': '182.0000', '2. high': '182.0000', '3. low': '181.9400', '4. close': '182.0000', '5. volume': '9667'}, '2023-06-12 19:36:00': {'1. open': '181.9000', '2. high': '182.0000', '3. low': '181.6700', '4. close': '182.0000', '5. volume': '12147'}, '2023-06-12 19:35:00': {'1. open': '182.3800', '2. high': '182.5000', '3. low': '181.9200', '4. close': '181.9200', '5. volume': '31649'}, '2023-06-12 19:34:00': {'1. open': '182.7900', '2. high': '182.8000', '3. low': '182.3000', '4. close': '182.5000', '5. volume': '28049'}, '2023-06-12 19:33:00': {'1. open': '183.3700', '2. high': '183.7000', '3. low': '182.8000', '4. close': '182.8000', '5. volume': '28676'}, '2023-06-12 19:32:00': {'1. open': '183.4500', '2. high': '183.5001', '3. low': '183.3700', '4. close': '183.5001', '5. volume': '5271'}, '2023-06-12 19:31:00': {'1. open': '183.7000', '2. high': '183.8900', '3. low': '183.3600', '4. close': '183.5000', '5. volume': '11708'}, '2023-06-12 19:30:00': {'1. open': '183.8800', '2. high': '183.9900', '3. low': '183.6200', '4. close': '183.7000', '5. volume': '15165'}, '2023-06-12 19:29:00': {'1. open': '184.0000', '2. high': '184.0300', '3. low': '183.7900', '4. close': '183.7900', '5. volume': '37795'}, '2023-06-12 19:28:00': {'1. open': '184.1100', '2. high': '184.1100', '3. low': '183.9900', '4. close': '183.9900', '5. volume': '8852'}, '2023-06-12 19:27:00': {'1. open': '184.2800', '2. high': '184.2800', '3. low': '184.0500', '4. close': '184.0500', '5. volume': '7256'}, '2023-06-12 19:26:00': {'1. open': '184.3500', '2. high': '184.3500', '3. low': '184.1200', '4. close': '184.1200', '5. volume': '9281'}, '2023-06-12 19:25:00': {'1. open': '184.3400', '2. high': '184.3400', '3. low': '184.3300', '4. close': '184.3300', '5. volume': '427'}, '2023-06-12 19:24:00': {'1. open': '184.3000', '2. high': '184.3400', '3. low': '184.3000', '4. close': '184.3400', '5. volume': '529'}, '2023-06-12 19:23:00': {'1. open': '184.3500', '2. high': '184.3500', '3. low': '184.3100', '4. close': '184.3500', '5. volume': '679'}, '2023-06-12 19:22:00': {'1. open': '184.3500', '2. high': '184.3500', '3. low': '184.3500', '4. close': '184.3500', '5. volume': '650'}, '2023-06-12 19:21:00': {'1. open': '184.3400', '2. high': '184.3500', '3. low': '184.3000', '4. close': '184.3000', '5. volume': '4585'}, '2023-06-12 19:20:00': {'1. open': '184.2900', '2. high': '184.3300', '3. low': '184.2900', '4. close': '184.3300', '5. volume': '2204'}, '2023-06-12 19:18:00': {'1. open': '184.2600', '2. high': '184.2600', '3. low': '184.2600', '4. close': '184.2600', '5. volume': '207'}, '2023-06-12 19:17:00': {'1. open': '184.2700', '2. high': '184.2900', '3. low': '184.2700', '4. close': '184.2900', '5. volume': '779'}, '2023-06-12 19:16:00': {'1. open': '184.2300', '2. high': '184.2300', '3. low': '184.2300', '4. close': '184.2300', '5. volume': '399'}, '2023-06-12 19:15:00': {'1. open': '184.2000', '2. high': '184.2000', '3. low': '184.1700', '4. close': '184.1700', '5. volume': '807'}, '2023-06-12 19:14:00': {'1. open': '184.2000', '2. high': '184.2000', '3. low': '184.1700', '4. close': '184.1700', '5. volume': '1518'}, '2023-06-12 19:13:00': {'1. open': '184.2400', '2. high': '184.2400', '3. low': '184.2200', '4. close': '184.2200', '5. volume': '780'}, '2023-06-12 19:12:00': {'1. open': '184.2500', '2. high': '184.2500', '3. low': '184.2500', '4. close': '184.2500', '5. volume': '213'}, '2023-06-12 19:09:00': {'1. open': '184.2700', '2. high': '184.2700', '3. low': '184.2500', '4. close': '184.2500', '5. volume': '2209'}, '2023-06-12 19:07:00': {'1. open': '184.2900', '2. high': '184.2900', '3. low': '184.2700', '4. close': '184.2700', '5. volume': '275'}, '2023-06-12 19:06:00': {'1. open': '184.2700', '2. high': '184.2700', '3. low': '184.2700', '4. close': '184.2700', '5. volume': '509'}, '2023-06-12 19:05:00': {'1. open': '184.2500', '2. high': '184.2500', '3. low': '184.2500', '4. close': '184.2500', '5. volume': '382'}, '2023-06-12 19:04:00': {'1. open': '184.2300', '2. high': '184.2300', '3. low': '184.2300', '4. close': '184.2300', '5. volume': '326'}, '2023-06-12 19:01:00': {'1. open': '184.2000', '2. high': '184.2500', '3. low': '184.2000', '4. close': '184.2500', '5. volume': '667'}, '2023-06-12 19:00:00': {'1. open': '184.2900', '2. high': '184.2900', '3. low': '184.2800', '4. close': '184.2800', '5. volume': '1777'}, '2023-06-12 18:59:00': {'1. open': '184.1900', '2. high': '184.2800', '3. low': '184.1900', '4. close': '184.2800', '5. volume': '546'}, '2023-06-12 18:58:00': {'1. open': '184.1910', '2. high': '184.1910', '3. low': '184.1910', '4. close': '184.1910', '5. volume': '579'}, '2023-06-12 18:57:00': {'1. open': '184.2800', '2. high': '184.2800', '3. low': '184.1700', '4. close': '184.1700', '5. volume': '442'}, '2023-06-12 18:56:00': {'1. open': '184.2100', '2. high': '184.2500', '3. low': '184.2100', '4. close': '184.2500', '5. volume': '1538'}, '2023-06-12 18:53:00': {'1. open': '184.1700', '2. high': '184.1700', '3. low': '184.1700', '4. close': '184.1700', '5. volume': '595'}, '2023-06-12 18:50:00': {'1. open': '184.1500', '2. high': '184.2336', '3. low': '184.1500', '4. close': '184.2336', '5. volume': '1038'}, '2023-06-12 18:49:00': {'1. open': '184.2100', '2. high': '184.2100', '3. low': '184.2100', '4. close': '184.2100', '5. volume': '126'}, '2023-06-12 18:48:00': {'1. open': '184.2400', '2. high': '184.2600', '3. low': '184.1502', '4. close': '184.2600', '5. volume': '3190'}, '2023-06-12 18:47:00': {'1. open': '184.2800', '2. high': '184.2800', '3. low': '184.2500', '4. close': '184.2500', '5. volume': '1538'}, '2023-06-12 18:46:00': {'1. open': '184.1500', '2. high': '184.2500', '3. low': '184.1500', '4. close': '184.2500', '5. volume': '5714'}, '2023-06-12 18:45:00': {'1. open': '184.0700', '2. high': '184.1500', '3. low': '184.0700', '4. close': '184.1500', '5. volume': '2297'}, '2023-06-12 18:44:00': {'1. open': '184.0112', '2. high': '184.0112', '3. low': '184.0112', '4. close': '184.0112', '5. volume': '544'}, '2023-06-12 18:43:00': {'1. open': '184.0500', '2. high': '184.0500', '3. low': '184.0219', '4. close': '184.0219', '5. volume': '1174'}, '2023-06-12 18:41:00': {'1. open': '184.0500', '2. high': '184.0500', '3. low': '184.0500', '4. close': '184.0500', '5. volume': '435'}, '2023-06-12 18:40:00': {'1. open': '184.0500', '2. high': '184.0500', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '2473'}, '2023-06-12 18:37:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '2950'}, '2023-06-12 18:36:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '733'}, '2023-06-12 18:34:00': {'1. open': '184.0388', '2. high': '184.0388', '3. low': '184.0388', '4. close': '184.0388', '5. volume': '393'}, '2023-06-12 18:33:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '216'}, '2023-06-12 18:31:00': {'1. open': '184.0500', '2. high': '184.0500', '3. low': '184.0500', '4. close': '184.0500', '5. volume': '180'}, '2023-06-12 18:30:00': {'1. open': '184.0500', '2. high': '184.0500', '3. low': '184.0500', '4. close': '184.0500', '5. volume': '1298'}, '2023-06-12 18:29:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '385'}, '2023-06-12 18:25:00': {'1. open': '184.0200', '2. high': '184.0400', '3. low': '184.0200', '4. close': '184.0400', '5. volume': '1967'}, '2023-06-12 18:24:00': {'1. open': '184.0064', '2. high': '184.0064', '3. low': '183.9800', '4. close': '183.9800', '5. volume': '272'}, '2023-06-12 18:23:00': {'1. open': '184.0200', '2. high': '184.0200', '3. low': '184.0200', '4. close': '184.0200', '5. volume': '569'}, '2023-06-12 18:22:00': {'1. open': '184.0000', '2. high': '184.0200', '3. low': '184.0000', '4. close': '184.0200', '5. volume': '1835'}, '2023-06-12 18:18:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '454'}, '2023-06-12 18:15:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '764'}, '2023-06-12 18:14:00': {'1. open': '183.9905', '2. high': '183.9905', '3. low': '183.9905', '4. close': '183.9905', '5. volume': '918'}, '2023-06-12 18:12:00': {'1. open': '184.0100', '2. high': '184.0100', '3. low': '184.0100', '4. close': '184.0100', '5. volume': '1340'}, '2023-06-12 18:09:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '1372'}, '2023-06-12 18:08:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '767'}, '2023-06-12 18:07:00': {'1. open': '184.0400', '2. high': '184.0400', '3. low': '184.0400', '4. close': '184.0400', '5. volume': '326'}, '2023-06-12 18:06:00': {'1. open': '184.0000', '2. high': '184.0000', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '246'}, '2023-06-12 18:05:00': {'1. open': '184.0104', '2. high': '184.0104', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '1363'}, '2023-06-12 18:02:00': {'1. open': '184.0100', '2. high': '184.0300', '3. low': '184.0000', '4. close': '184.0000', '5. volume': '2113'}, '2023-06-12 17:59:00': {'1. open': '184.0000', '2. high': '184.0600', '3. low': '184.0000', '4. close': '184.0600', '5. volume': '1485'}, '2023-06-12 17:57:00': {'1. open': '184.0200', '2. high': '184.0201', '3. low': '184.0200', '4. close': '184.0201', '5. volume': '1120'}, '2023-06-12 17:56:00': {'1. open': '184.0300', '2. high': '184.0300', '3. low': '183.9900', '4. close': '183.9900', '5. volume': '1467'}, '2023-06-12 17:54:00': {'1. open': '183.9800', '2. high': '184.0000', '3. low': '183.9800', '4. close': '184.0000', '5. volume': '19847'}, '2023-06-12 17:53:00': {'1. open': '183.9500', '2. high': '183.9500', '3. low': '183.9499', '4. close': '183.9499', '5. volume': '1003'}, '2023-06-12 17:52:00': {'1. open': '183.9500', '2. high': '183.9500', '3. low': '183.9300', '4. close': '183.9300', '5. volume': '337'}, '2023-06-12 17:50:00': {'1. open': '183.9200', '2. high': '183.9200', '3. low': '183.9200', '4. close': '183.9200', '5. volume': '228'}, '2023-06-12 17:49:00': {'1. open': '183.9700', '2. high': '183.9800', '3. low': '183.9300', '4. close': '183.9300', '5. volume': '1671'}, '2023-06-12 17:48:00': {'1. open': '183.9201', '2. high': '183.9201', '3. low': '183.9201', '4. close': '183.9201', '5. volume': '181'}, '2023-06-12 17:47:00': {'1. open': '183.9500', '2. high': '183.9500', '3. low': '183.9200', '4. close': '183.9300', '5. volume': '1764'}}

        open      high       low     close  volume           timestamp
0   182.4600  182.5500  182.4401  182.5099    9319 2023-06-12 19:59:00
1   182.5400  182.5496  182.1000  182.5400   20613 2023-06-12 19:58:00
2   182.5200  182.5900  182.5200  182.5500   10400 2023-06-12 19:57:00
3   182.5000  182.5800  182.4800  182.5800    6868 2023-06-12 19:56:00
4   182.3000  182.7000  182.2000  182.6900   15533 2023-06-12 19:55:00
..       ...       ...       ...       ...     ...                 ...
95  183.9500  183.9500  183.9300  183.9300     337 2023-06-12 17:52:00
96  183.9200  183.9200  183.9200  183.9200     228 2023-06-12 17:50:00
97  183.9700  183.9800  183.9300  183.9300    1671 2023-06-12 17:49:00
98  183.9201  183.9201  183.9201  183.9201     181 2023-06-12 17:48:00
99  183.9500  183.9500  183.9200  183.9300    1764 2023-06-12 17:47:00

[100 rows x 6 columns]

In [267]:
'GOOGL' in script_data

True

In [268]:
'AAPL' in script_data

True

In [269]:
'NVDA' in script_data

False

In [270]:
print(script_data['GOOGL'])

{'2023-06-12 19:58:00': {'1. open': '123.8300', '2. high': '123.8300', '3. low': '123.8300', '4. close': '123.8300', '5. volume': '434'}, '2023-06-12 19:57:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '663'}, '2023-06-12 19:56:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '439'}, '2023-06-12 19:55:00': {'1. open': '123.8400', '2. high': '123.8400', '3. low': '123.8400', '4. close': '123.8400', '5. volume': '130'}, '2023-06-12 19:54:00': {'1. open': '123.8800', '2. high': '123.8800', '3. low': '123.8800', '4. close': '123.8800', '5. volume': '335'}, '2023-06-12 19:53:00': {'1. open': '123.8200', '2. high': '123.8200', '3. low': '123.8200', '4. close': '123.8200', '5. volume': '464'}, '2023-06-12 19:52:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '226'}, '2023-06-12 19:50:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '627'}, '2023-06-12 19:49:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '110'}, '2023-06-12 19:47:00': {'1. open': '123.9200', '2. high': '123.9200', '3. low': '123.9200', '4. close': '123.9200', '5. volume': '1348'}, '2023-06-12 19:46:00': {'1. open': '123.9200', '2. high': '123.9200', '3. low': '123.9200', '4. close': '123.9200', '5. volume': '635'}, '2023-06-12 19:44:00': {'1. open': '123.9500', '2. high': '123.9500', '3. low': '123.9500', '4. close': '123.9500', '5. volume': '1002'}, '2023-06-12 19:43:00': {'1. open': '123.9500', '2. high': '123.9500', '3. low': '123.9500', '4. close': '123.9500', '5. volume': '525'}, '2023-06-12 19:40:00': {'1. open': '123.9101', '2. high': '123.9101', '3. low': '123.9101', '4. close': '123.9101', '5. volume': '138'}, '2023-06-12 19:39:00': {'1. open': '123.9400', '2. high': '123.9400', '3. low': '123.9400', '4. close': '123.9400', '5. volume': '152'}, '2023-06-12 19:38:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '862'}, '2023-06-12 19:36:00': {'1. open': '123.9700', '2. high': '123.9700', '3. low': '123.9700', '4. close': '123.9700', '5. volume': '1367'}, '2023-06-12 19:35:00': {'1. open': '123.9700', '2. high': '123.9700', '3. low': '123.9700', '4. close': '123.9700', '5. volume': '1056'}, '2023-06-12 19:34:00': {'1. open': '123.9500', '2. high': '123.9800', '3. low': '123.9500', '4. close': '123.9800', '5. volume': '1696'}, '2023-06-12 19:33:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '1799'}, '2023-06-12 19:28:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '149'}, '2023-06-12 19:27:00': {'1. open': '123.7700', '2. high': '123.7700', '3. low': '123.7600', '4. close': '123.7600', '5. volume': '431'}, '2023-06-12 19:17:00': {'1. open': '123.9400', '2. high': '123.9400', '3. low': '123.9400', '4. close': '123.9400', '5. volume': '532'}, '2023-06-12 19:13:00': {'1. open': '123.8000', '2. high': '123.8000', '3. low': '123.8000', '4. close': '123.8000', '5. volume': '348'}, '2023-06-12 19:03:00': {'1. open': '123.8800', '2. high': '123.8800', '3. low': '123.8800', '4. close': '123.8800', '5. volume': '222'}, '2023-06-12 19:01:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '107'}, '2023-06-12 19:00:00': {'1. open': '123.9000', '2. high': '123.9000', '3. low': '123.9000', '4. close': '123.9000', '5. volume': '276'}, '2023-06-12 18:59:00': {'1. open': '123.9400', '2. high': '123.9400', '3. low': '123.9400', '4. close': '123.9400', '5. volume': '148'}, '2023-06-12 18:56:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '190'}, '2023-06-12 18:53:00': {'1. open': '123.8000', '2. high': '123.8000', '3. low': '123.8000', '4. close': '123.8000', '5. volume': '560'}, '2023-06-12 18:49:00': {'1. open': '123.8000', '2. high': '123.8000', '3. low': '123.8000', '4. close': '123.8000', '5. volume': '1003'}, '2023-06-12 18:48:00': {'1. open': '123.8500', '2. high': '123.8500', '3. low': '123.8500', '4. close': '123.8500', '5. volume': '1245'}, '2023-06-12 18:46:00': {'1. open': '123.8000', '2. high': '123.8500', '3. low': '123.8000', '4. close': '123.8500', '5. volume': '2633'}, '2023-06-12 18:45:00': {'1. open': '123.8200', '2. high': '123.8200', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '538'}, '2023-06-12 18:44:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '525'}, '2023-06-12 18:43:00': {'1. open': '123.7900', '2. high': '123.8000', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '1528'}, '2023-06-12 18:33:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '375'}, '2023-06-12 18:32:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '255'}, '2023-06-12 18:30:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '299'}, '2023-06-12 18:28:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7400', '4. close': '123.7500', '5. volume': '504'}, '2023-06-12 18:25:00': {'1. open': '123.8104', '2. high': '123.8104', '3. low': '123.8104', '4. close': '123.8104', '5. volume': '193'}, '2023-06-12 18:24:00': {'1. open': '123.8300', '2. high': '123.8300', '3. low': '123.8300', '4. close': '123.8300', '5. volume': '209'}, '2023-06-12 18:22:00': {'1. open': '123.7412', '2. high': '123.7412', '3. low': '123.7400', '4. close': '123.7400', '5. volume': '515'}, '2023-06-12 18:18:00': {'1. open': '123.7425', '2. high': '123.7425', '3. low': '123.7425', '4. close': '123.7425', '5. volume': '132'}, '2023-06-12 18:16:00': {'1. open': '123.7424', '2. high': '123.7424', '3. low': '123.7424', '4. close': '123.7424', '5. volume': '262'}, '2023-06-12 18:14:00': {'1. open': '123.8153', '2. high': '123.8200', '3. low': '123.8153', '4. close': '123.8200', '5. volume': '413'}, '2023-06-12 18:13:00': {'1. open': '123.7300', '2. high': '123.7400', '3. low': '123.7300', '4. close': '123.7400', '5. volume': '410'}, '2023-06-12 18:12:00': {'1. open': '123.7300', '2. high': '123.7300', '3. low': '123.7300', '4. close': '123.7300', '5. volume': '296'}, '2023-06-12 18:08:00': {'1. open': '123.6360', '2. high': '123.7398', '3. low': '123.6360', '4. close': '123.7398', '5. volume': '1368'}, '2023-06-12 18:06:00': {'1. open': '123.7388', '2. high': '123.7388', '3. low': '123.7388', '4. close': '123.7388', '5. volume': '138'}, '2023-06-12 18:05:00': {'1. open': '123.6700', '2. high': '123.6700', '3. low': '123.6700', '4. close': '123.6700', '5. volume': '437'}, '2023-06-12 18:01:00': {'1. open': '123.7000', '2. high': '123.7399', '3. low': '123.7000', '4. close': '123.7399', '5. volume': '750'}, '2023-06-12 17:56:00': {'1. open': '123.7000', '2. high': '123.7000', '3. low': '123.7000', '4. close': '123.7000', '5. volume': '526'}, '2023-06-12 17:55:00': {'1. open': '123.6900', '2. high': '123.6900', '3. low': '123.6900', '4. close': '123.6900', '5. volume': '156'}, '2023-06-12 17:54:00': {'1. open': '123.7000', '2. high': '123.7000', '3. low': '123.7000', '4. close': '123.7000', '5. volume': '154'}, '2023-06-12 17:52:00': {'1. open': '123.6571', '2. high': '123.6571', '3. low': '123.6571', '4. close': '123.6571', '5. volume': '283'}, '2023-06-12 17:49:00': {'1. open': '123.6700', '2. high': '123.7400', '3. low': '123.6700', '4. close': '123.7400', '5. volume': '875'}, '2023-06-12 17:47:00': {'1. open': '123.6400', '2. high': '123.6400', '3. low': '123.6400', '4. close': '123.6400', '5. volume': '263'}, '2023-06-12 17:46:00': {'1. open': '123.6400', '2. high': '123.6400', '3. low': '123.6400', '4. close': '123.6400', '5. volume': '218'}, '2023-06-12 17:44:00': {'1. open': '123.6100', '2. high': '123.6200', '3. low': '123.6100', '4. close': '123.6200', '5. volume': '282'}, '2023-06-12 17:43:00': {'1. open': '123.6102', '2. high': '123.6102', '3. low': '123.6100', '4. close': '123.6100', '5. volume': '745'}, '2023-06-12 17:41:00': {'1. open': '123.6500', '2. high': '123.6500', '3. low': '123.6500', '4. close': '123.6500', '5. volume': '1010'}, '2023-06-12 17:40:00': {'1. open': '123.6200', '2. high': '123.6200', '3. low': '123.6200', '4. close': '123.6200', '5. volume': '368'}, '2023-06-12 17:39:00': {'1. open': '123.8400', '2. high': '123.8400', '3. low': '123.8400', '4. close': '123.8400', '5. volume': '845'}, '2023-06-12 17:38:00': {'1. open': '123.6200', '2. high': '123.6700', '3. low': '123.6000', '4. close': '123.6000', '5. volume': '789'}, '2023-06-12 17:37:00': {'1. open': '123.7900', '2. high': '123.8400', '3. low': '123.6400', '4. close': '123.6400', '5. volume': '5393'}, '2023-06-12 17:36:00': {'1. open': '123.7899', '2. high': '123.7899', '3. low': '123.7700', '4. close': '123.7700', '5. volume': '1201'}, '2023-06-12 17:33:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '105'}, '2023-06-12 17:30:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '1059'}, '2023-06-12 17:23:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '381'}, '2023-06-12 17:17:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '286'}, '2023-06-12 17:15:00': {'1. open': '123.7799', '2. high': '123.7799', '3. low': '123.7799', '4. close': '123.7799', '5. volume': '521'}, '2023-06-12 17:14:00': {'1. open': '123.7100', '2. high': '123.7201', '3. low': '123.7100', '4. close': '123.7201', '5. volume': '564'}, '2023-06-12 17:13:00': {'1. open': '123.7100', '2. high': '123.7100', '3. low': '123.7100', '4. close': '123.7100', '5. volume': '396'}, '2023-06-12 17:12:00': {'1. open': '123.6400', '2. high': '123.7100', '3. low': '123.6400', '4. close': '123.7100', '5. volume': '674476'}, '2023-06-12 17:05:00': {'1. open': '123.7600', '2. high': '123.7600', '3. low': '123.7600', '4. close': '123.7600', '5. volume': '362'}, '2023-06-12 17:04:00': {'1. open': '123.7600', '2. high': '123.7600', '3. low': '123.7600', '4. close': '123.7600', '5. volume': '551'}, '2023-06-12 16:59:00': {'1. open': '123.7400', '2. high': '123.7900', '3. low': '123.7400', '4. close': '123.7800', '5. volume': '1051'}, '2023-06-12 16:58:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '1416'}, '2023-06-12 16:57:00': {'1. open': '123.8200', '2. high': '123.8200', '3. low': '123.8100', '4. close': '123.8100', '5. volume': '439'}, '2023-06-12 16:55:00': {'1. open': '123.7500', '2. high': '123.7500', '3. low': '123.7500', '4. close': '123.7500', '5. volume': '237'}, '2023-06-12 16:54:00': {'1. open': '123.7901', '2. high': '123.7901', '3. low': '123.7901', '4. close': '123.7901', '5. volume': '548'}, '2023-06-12 16:53:00': {'1. open': '123.8400', '2. high': '123.8400', '3. low': '123.8400', '4. close': '123.8400', '5. volume': '320'}, '2023-06-12 16:52:00': {'1. open': '123.8500', '2. high': '123.8600', '3. low': '123.8300', '4. close': '123.8300', '5. volume': '3051'}, '2023-06-12 16:51:00': {'1. open': '123.8793', '2. high': '123.8900', '3. low': '123.8501', '4. close': '123.8501', '5. volume': '156990'}, '2023-06-12 16:50:00': {'1. open': '123.8800', '2. high': '123.8800', '3. low': '123.8800', '4. close': '123.8800', '5. volume': '1166'}, '2023-06-12 16:48:00': {'1. open': '123.7900', '2. high': '123.9000', '3. low': '123.7900', '4. close': '123.8900', '5. volume': '6984'}, '2023-06-12 16:45:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.6400', '4. close': '123.7900', '5. volume': '3105'}, '2023-06-12 16:44:00': {'1. open': '123.7900', '2. high': '123.7900', '3. low': '123.7900', '4. close': '123.7900', '5. volume': '118'}, '2023-06-12 16:42:00': {'1. open': '123.7300', '2. high': '123.7300', '3. low': '123.7300', '4. close': '123.7300', '5. volume': '881'}, '2023-06-12 16:40:00': {'1. open': '123.7100', '2. high': '123.7200', '3. low': '123.7000', '4. close': '123.7200', '5. volume': '5309'}, '2023-06-12 16:39:00': {'1. open': '123.7000', '2. high': '123.7100', '3. low': '123.7000', '4. close': '123.7100', '5. volume': '508'}, '2023-06-12 16:38:00': {'1. open': '123.6900', '2. high': '123.7000', '3. low': '123.6900', '4. close': '123.7000', '5. volume': '1387'}, '2023-06-12 16:37:00': {'1. open': '123.6900', '2. high': '123.6900', '3. low': '123.6900', '4. close': '123.6900', '5. volume': '951'}, '2023-06-12 16:35:00': {'1. open': '123.6900', '2. high': '123.6900', '3. low': '123.6900', '4. close': '123.6900', '5. volume': '261'}, '2023-06-12 16:34:00': {'1. open': '123.7300', '2. high': '123.7300', '3. low': '123.7300', '4. close': '123.7300', '5. volume': '148'}, '2023-06-12 16:31:00': {'1. open': '123.6848', '2. high': '123.6848', '3. low': '123.6848', '4. close': '123.6848', '5. volume': '594'}, '2023-06-12 16:28:00': {'1. open': '123.7396', '2. high': '123.7400', '3. low': '123.7396', '4. close': '123.7400', '5. volume': '1527'}, '2023-06-12 16:27:00': {'1. open': '123.7067', '2. high': '123.7100', '3. low': '123.7004', '4. close': '123.7004', '5. volume': '591'}, '2023-06-12 16:26:00': {'1. open': '123.7200', '2. high': '123.7200', '3. low': '123.7200', '4. close': '123.7200', '5. volume': '252'}}

In [271]:
indicator1(script_data.convert_intraday_data('GOOGL'), timeperiod=5)

             timestamp  indicator
0  2023-06-12 19:58:00  123.83000
1  2023-06-12 19:57:00  123.84000
2  2023-06-12 19:56:00  123.86000
3  2023-06-12 19:55:00  123.85500
4  2023-06-12 19:54:00  123.86000
..                 ...        ...
95 2023-06-12 16:34:00  123.70400
96 2023-06-12 16:31:00  123.69896
97 2023-06-12 16:28:00  123.70696
98 2023-06-12 16:27:00  123.70904
99 2023-06-12 16:26:00  123.71504

[100 rows x 2 columns]

In [272]:
indicator_data = indicator1(script_data.convert_intraday_data('AAPL'), timeperiod=5)
indicator_data

             timestamp   indicator
0  2023-06-12 19:59:00  182.509900
1  2023-06-12 19:58:00  182.524950
2  2023-06-12 19:57:00  182.533300
3  2023-06-12 19:56:00  182.544975
4  2023-06-12 19:55:00  182.573980
..                 ...         ...
95 2023-06-12 17:52:00  183.978000
96 2023-06-12 17:50:00  183.957980
97 2023-06-12 17:49:00  183.945980
98 2023-06-12 17:48:00  183.930000
99 2023-06-12 17:47:00  183.926020

[100 rows x 2 columns]

In [273]:
class Strategy:
    def __init__(self, api_key):
        self.api_key = api_key
        self.script_data = ScriptData(api_key)

    def fetch_intraday_data(self, script):
        self.script_data.fetch_intraday_data(script)
        self.df = self.script_data.convert_intraday_data(script)

    def compute_indicator_data(self, timeperiod):
        self.indicator_df = indicator1(self.df, timeperiod)

    def generate_signals(self):
        signals = pd.DataFrame(index=self.df.index)
        signals['timestamp'] = self.df['timestamp']
        signals['signal'] = 'NO_SIGNAL'

        for i in range(1, len(self.df)):
            if self.indicator_df['indicator'].iloc[i] > self.df['close'].iloc[i] and self.indicator_df['indicator'].iloc[i-1] < self.df['close'].iloc[i-1]:
                signals.loc[i, 'signal'] = 'BUY'
            elif self.indicator_df['indicator'].iloc[i] < self.df['close'].iloc[i] and self.indicator_df['indicator'].iloc[i-1] > self.df['close'].iloc[i-1]:
                signals.loc[i, 'signal'] = 'SELL'

        self.signals = signals

    def print_signals(self):
        filtered_signals = self.signals.loc[self.signals['signal'].isin(['BUY', 'SELL'])]
        print(filtered_signals)

In [274]:
strategy = Strategy('NVDA')
strategy.fetch_intraday_data('NVDA')
strategy.compute_indicator_data(5)
strategy.generate_signals()
strategy.print_signals()

{'2023-06-12 19:59:00': {'1. open': '395.5000', '2. high': '395.7000', '3. low': '395.5000', '4. close': '395.7000', '5. volume': '2931'}, '2023-06-12 19:58:00': {'1. open': '395.6000', '2. high': '395.6000', '3. low': '395.4900', '4. close': '395.4900', '5. volume': '1277'}, '2023-06-12 19:57:00': {'1. open': '395.6500', '2. high': '395.7000', '3. low': '395.6000', '4. close': '395.6000', '5. volume': '2057'}, '2023-06-12 19:56:00': {'1. open': '395.6900', '2. high': '395.6900', '3. low': '395.6500', '4. close': '395.6500', '5. volume': '692'}, '2023-06-12 19:55:00': {'1. open': '395.7000', '2. high': '395.7000', '3. low': '395.7000', '4. close': '395.7000', '5. volume': '445'}, '2023-06-12 19:54:00': {'1. open': '395.7700', '2. high': '395.7700', '3. low': '395.6000', '4. close': '395.7200', '5. volume': '1256'}, '2023-06-12 19:53:00': {'1. open': '395.4100', '2. high': '395.5800', '3. low': '395.4100', '4. close': '395.5800', '5. volume': '1018'}, '2023-06-12 19:52:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.4000', '4. close': '395.4000', '5. volume': '963'}, '2023-06-12 19:51:00': {'1. open': '395.3500', '2. high': '395.3500', '3. low': '395.3000', '4. close': '395.3000', '5. volume': '1568'}, '2023-06-12 19:50:00': {'1. open': '395.4500', '2. high': '395.4500', '3. low': '395.3400', '4. close': '395.3400', '5. volume': '2258'}, '2023-06-12 19:49:00': {'1. open': '395.3000', '2. high': '395.4100', '3. low': '395.3000', '4. close': '395.4100', '5. volume': '1828'}, '2023-06-12 19:47:00': {'1. open': '395.2700', '2. high': '395.3800', '3. low': '395.2200', '4. close': '395.3800', '5. volume': '2667'}, '2023-06-12 19:46:00': {'1. open': '395.3200', '2. high': '395.3200', '3. low': '395.3200', '4. close': '395.3200', '5. volume': '491'}, '2023-06-12 19:45:00': {'1. open': '395.2600', '2. high': '395.2600', '3. low': '395.2600', '4. close': '395.2600', '5. volume': '353'}, '2023-06-12 19:44:00': {'1. open': '395.2500', '2. high': '395.3700', '3. low': '395.2500', '4. close': '395.3600', '5. volume': '1095'}, '2023-06-12 19:43:00': {'1. open': '395.4100', '2. high': '395.4100', '3. low': '395.2200', '4. close': '395.2200', '5. volume': '1017'}, '2023-06-12 19:41:00': {'1. open': '395.2500', '2. high': '395.2600', '3. low': '395.2500', '4. close': '395.2500', '5. volume': '1150'}, '2023-06-12 19:40:00': {'1. open': '395.3100', '2. high': '395.3100', '3. low': '395.2100', '4. close': '395.2100', '5. volume': '1361'}, '2023-06-12 19:39:00': {'1. open': '395.4100', '2. high': '395.4100', '3. low': '395.3600', '4. close': '395.3600', '5. volume': '863'}, '2023-06-12 19:38:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.4000', '4. close': '395.4000', '5. volume': '392'}, '2023-06-12 19:37:00': {'1. open': '395.4100', '2. high': '395.4100', '3. low': '395.4100', '4. close': '395.4100', '5. volume': '544'}, '2023-06-12 19:36:00': {'1. open': '395.7900', '2. high': '395.7900', '3. low': '395.4000', '4. close': '395.4600', '5. volume': '4118'}, '2023-06-12 19:35:00': {'1. open': '395.7000', '2. high': '395.7000', '3. low': '395.6900', '4. close': '395.7000', '5. volume': '968'}, '2023-06-12 19:34:00': {'1. open': '395.6000', '2. high': '395.8000', '3. low': '395.6000', '4. close': '395.6000', '5. volume': '1956'}, '2023-06-12 19:33:00': {'1. open': '395.4700', '2. high': '395.6500', '3. low': '395.4700', '4. close': '395.6000', '5. volume': '3920'}, '2023-06-12 19:32:00': {'1. open': '395.3100', '2. high': '395.4000', '3. low': '395.3100', '4. close': '395.4000', '5. volume': '2605'}, '2023-06-12 19:29:00': {'1. open': '395.3500', '2. high': '395.4000', '3. low': '395.3500', '4. close': '395.4000', '5. volume': '924'}, '2023-06-12 19:28:00': {'1. open': '395.3000', '2. high': '395.3000', '3. low': '395.3000', '4. close': '395.3000', '5. volume': '361'}, '2023-06-12 19:25:00': {'1. open': '395.1999', '2. high': '395.2000', '3. low': '395.1999', '4. close': '395.2000', '5. volume': '933'}, '2023-06-12 19:24:00': {'1. open': '395.2000', '2. high': '395.2000', '3. low': '395.2000', '4. close': '395.2000', '5. volume': '167'}, '2023-06-12 19:23:00': {'1. open': '395.3000', '2. high': '395.3000', '3. low': '395.1900', '4. close': '395.3000', '5. volume': '1789'}, '2023-06-12 19:21:00': {'1. open': '395.2500', '2. high': '395.2500', '3. low': '395.2500', '4. close': '395.2500', '5. volume': '152'}, '2023-06-12 19:20:00': {'1. open': '395.2100', '2. high': '395.3000', '3. low': '395.2100', '4. close': '395.2100', '5. volume': '1070'}, '2023-06-12 19:18:00': {'1. open': '395.3500', '2. high': '395.3500', '3. low': '395.3500', '4. close': '395.3500', '5. volume': '704'}, '2023-06-12 19:17:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.4000', '4. close': '395.4000', '5. volume': '4375'}, '2023-06-12 19:16:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.2000', '4. close': '395.2000', '5. volume': '1894'}, '2023-06-12 19:15:00': {'1. open': '395.4200', '2. high': '395.4200', '3. low': '395.4100', '4. close': '395.4100', '5. volume': '670'}, '2023-06-12 19:14:00': {'1. open': '395.4200', '2. high': '395.4200', '3. low': '395.4200', '4. close': '395.4200', '5. volume': '249'}, '2023-06-12 19:13:00': {'1. open': '395.4400', '2. high': '395.4400', '3. low': '395.4200', '4. close': '395.4200', '5. volume': '822'}, '2023-06-12 19:10:00': {'1. open': '395.4500', '2. high': '395.4500', '3. low': '395.4500', '4. close': '395.4500', '5. volume': '304'}, '2023-06-12 19:09:00': {'1. open': '395.3600', '2. high': '395.3600', '3. low': '395.3600', '4. close': '395.3600', '5. volume': '289'}, '2023-06-12 19:08:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.4000', '4. close': '395.4000', '5. volume': '265'}, '2023-06-12 19:05:00': {'1. open': '395.4600', '2. high': '395.4600', '3. low': '395.3500', '4. close': '395.3500', '5. volume': '682'}, '2023-06-12 19:02:00': {'1. open': '395.2900', '2. high': '395.2900', '3. low': '395.2900', '4. close': '395.2900', '5. volume': '525'}, '2023-06-12 18:59:00': {'1. open': '395.4539', '2. high': '395.4539', '3. low': '395.4539', '4. close': '395.4539', '5. volume': '156'}, '2023-06-12 18:58:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.4000', '4. close': '395.4000', '5. volume': '244'}, '2023-06-12 18:54:00': {'1. open': '395.2900', '2. high': '395.2900', '3. low': '395.2900', '4. close': '395.2900', '5. volume': '320'}, '2023-06-12 18:53:00': {'1. open': '395.3700', '2. high': '395.3700', '3. low': '395.3700', '4. close': '395.3700', '5. volume': '568'}, '2023-06-12 18:52:00': {'1. open': '395.4000', '2. high': '395.4000', '3. low': '395.3979', '4. close': '395.3979', '5. volume': '301'}, '2023-06-12 18:51:00': {'1. open': '395.3817', '2. high': '395.4000', '3. low': '395.3800', '4. close': '395.3800', '5. volume': '1203'}, '2023-06-12 18:50:00': {'1. open': '395.2400', '2. high': '395.3000', '3. low': '395.2400', '4. close': '395.3000', '5. volume': '2522'}, '2023-06-12 18:49:00': {'1. open': '395.1800', '2. high': '395.1800', '3. low': '395.1800', '4. close': '395.1800', '5. volume': '137'}, '2023-06-12 18:48:00': {'1. open': '395.2000', '2. high': '395.2000', '3. low': '395.1800', '4. close': '395.1800', '5. volume': '1340'}, '2023-06-12 18:47:00': {'1. open': '395.1800', '2. high': '395.2000', '3. low': '395.1800', '4. close': '395.2000', '5. volume': '3489'}, '2023-06-12 18:46:00': {'1. open': '395.1900', '2. high': '395.2000', '3. low': '395.1900', '4. close': '395.2000', '5. volume': '1643'}, '2023-06-12 18:45:00': {'1. open': '395.0000', '2. high': '395.0600', '3. low': '395.0000', '4. close': '395.0600', '5. volume': '659'}, '2023-06-12 18:44:00': {'1. open': '395.0000', '2. high': '395.0000', '3. low': '395.0000', '4. close': '395.0000', '5. volume': '1669'}, '2023-06-12 18:43:00': {'1. open': '395.0000', '2. high': '395.0000', '3. low': '395.0000', '4. close': '395.0000', '5. volume': '1032'}, '2023-06-12 18:42:00': {'1. open': '395.0000', '2. high': '395.0000', '3. low': '395.0000', '4. close': '395.0000', '5. volume': '766'}, '2023-06-12 18:37:00': {'1. open': '394.8500', '2. high': '394.8500', '3. low': '394.8500', '4. close': '394.8500', '5. volume': '307'}, '2023-06-12 18:36:00': {'1. open': '394.8512', '2. high': '394.9900', '3. low': '394.8512', '4. close': '394.9900', '5. volume': '764'}, '2023-06-12 18:35:00': {'1. open': '394.8500', '2. high': '394.8500', '3. low': '394.8500', '4. close': '394.8500', '5. volume': '480'}, '2023-06-12 18:33:00': {'1. open': '394.8502', '2. high': '394.8600', '3. low': '394.8502', '4. close': '394.8600', '5. volume': '683'}, '2023-06-12 18:32:00': {'1. open': '394.9500', '2. high': '394.9900', '3. low': '394.9500', '4. close': '394.9900', '5. volume': '1219'}, '2023-06-12 18:30:00': {'1. open': '394.9900', '2. high': '394.9900', '3. low': '394.9500', '4. close': '394.9500', '5. volume': '511'}, '2023-06-12 18:29:00': {'1. open': '394.9500', '2. high': '394.9500', '3. low': '394.9500', '4. close': '394.9500', '5. volume': '334'}, '2023-06-12 18:27:00': {'1. open': '394.8900', '2. high': '394.8900', '3. low': '394.8900', '4. close': '394.8900', '5. volume': '682'}, '2023-06-12 18:26:00': {'1. open': '394.8300', '2. high': '394.8999', '3. low': '394.8300', '4. close': '394.8999', '5. volume': '709'}, '2023-06-12 18:25:00': {'1. open': '394.9000', '2. high': '394.9000', '3. low': '394.8300', '4. close': '394.8300', '5. volume': '609'}, '2023-06-12 18:24:00': {'1. open': '394.9000', '2. high': '394.9000', '3. low': '394.9000', '4. close': '394.9000', '5. volume': '676'}, '2023-06-12 18:23:00': {'1. open': '394.8501', '2. high': '394.9000', '3. low': '394.8501', '4. close': '394.9000', '5. volume': '371'}, '2023-06-12 18:19:00': {'1. open': '395.0130', '2. high': '395.0130', '3. low': '395.0130', '4. close': '395.0130', '5. volume': '488'}, '2023-06-12 18:18:00': {'1. open': '394.8900', '2. high': '394.8900', '3. low': '394.8900', '4. close': '394.8900', '5. volume': '640'}, '2023-06-12 18:16:00': {'1. open': '394.8900', '2. high': '394.8900', '3. low': '394.8900', '4. close': '394.8900', '5. volume': '10141'}, '2023-06-12 18:15:00': {'1. open': '394.8400', '2. high': '394.8400', '3. low': '394.8400', '4. close': '394.8400', '5. volume': '354'}, '2023-06-12 18:14:00': {'1. open': '394.9000', '2. high': '394.9001', '3. low': '394.8500', '4. close': '394.8500', '5. volume': '506'}, '2023-06-12 18:13:00': {'1. open': '394.9000', '2. high': '394.9000', '3. low': '394.9000', '4. close': '394.9000', '5. volume': '579'}, '2023-06-12 18:12:00': {'1. open': '395.1000', '2. high': '395.1000', '3. low': '394.9200', '4. close': '394.9200', '5. volume': '4960'}, '2023-06-12 18:11:00': {'1. open': '395.1000', '2. high': '395.1000', '3. low': '395.0200', '4. close': '395.0200', '5. volume': '1595'}, '2023-06-12 18:07:00': {'1. open': '395.1300', '2. high': '395.1300', '3. low': '395.1300', '4. close': '395.1300', '5. volume': '286'}, '2023-06-12 18:05:00': {'1. open': '395.1800', '2. high': '395.2000', '3. low': '395.1800', '4. close': '395.2000', '5. volume': '1220'}, '2023-06-12 18:02:00': {'1. open': '395.1026', '2. high': '395.1026', '3. low': '395.1026', '4. close': '395.1026', '5. volume': '685'}, '2023-06-12 17:59:00': {'1. open': '395.2000', '2. high': '395.2000', '3. low': '395.1875', '4. close': '395.1875', '5. volume': '575'}, '2023-06-12 17:58:00': {'1. open': '395.1900', '2. high': '395.2000', '3. low': '395.1500', '4. close': '395.2000', '5. volume': '1373'}, '2023-06-12 17:57:00': {'1. open': '395.0900', '2. high': '395.1600', '3. low': '395.0900', '4. close': '395.1500', '5. volume': '906'}, '2023-06-12 17:56:00': {'1. open': '395.0600', '2. high': '395.0600', '3. low': '395.0500', '4. close': '395.0500', '5. volume': '850'}, '2023-06-12 17:53:00': {'1. open': '395.1500', '2. high': '395.1500', '3. low': '395.1500', '4. close': '395.1500', '5. volume': '384'}, '2023-06-12 17:51:00': {'1. open': '395.0100', '2. high': '395.1300', '3. low': '395.0100', '4. close': '395.1300', '5. volume': '681'}, '2023-06-12 17:49:00': {'1. open': '395.1500', '2. high': '395.1500', '3. low': '395.1500', '4. close': '395.1500', '5. volume': '158'}, '2023-06-12 17:48:00': {'1. open': '395.1800', '2. high': '395.1800', '3. low': '395.0100', '4. close': '395.0100', '5. volume': '548'}, '2023-06-12 17:47:00': {'1. open': '395.0300', '2. high': '395.0300', '3. low': '395.0300', '4. close': '395.0300', '5. volume': '269'}, '2023-06-12 17:46:00': {'1. open': '395.1100', '2. high': '395.1100', '3. low': '395.0100', '4. close': '395.0100', '5. volume': '530'}, '2023-06-12 17:45:00': {'1. open': '395.1500', '2. high': '395.1500', '3. low': '395.1500', '4. close': '395.1500', '5. volume': '468'}, '2023-06-12 17:44:00': {'1. open': '395.1100', '2. high': '395.1100', '3. low': '395.1100', '4. close': '395.1100', '5. volume': '530'}, '2023-06-12 17:43:00': {'1. open': '395.1101', '2. high': '395.1101', '3. low': '395.1101', '4. close': '395.1101', '5. volume': '1064'}, '2023-06-12 17:42:00': {'1. open': '395.2500', '2. high': '395.2600', '3. low': '395.1800', '4. close': '395.1800', '5. volume': '662'}, '2023-06-12 17:41:00': {'1. open': '395.3797', '2. high': '395.3797', '3. low': '395.3797', '4. close': '395.3797', '5. volume': '393'}, '2023-06-12 17:40:00': {'1. open': '395.3000', '2. high': '395.3200', '3. low': '395.3000', '4. close': '395.3000', '5. volume': '1977'}, '2023-06-12 17:39:00': {'1. open': '395.3000', '2. high': '395.3000', '3. low': '395.3000', '4. close': '395.3000', '5. volume': '567'}, '2023-06-12 17:38:00': {'1. open': '395.2200', '2. high': '395.3300', '3. low': '395.2200', '4. close': '395.3300', '5. volume': '812'}}
             timestamp signal
2  2023-06-12 19:57:00   SELL
6  2023-06-12 19:53:00    BUY
10 2023-06-12 19:49:00   SELL
12 2023-06-12 19:46:00    BUY
14 2023-06-12 19:44:00   SELL
15 2023-06-12 19:43:00    BUY
18 2023-06-12 19:39:00   SELL
25 2023-06-12 19:32:00    BUY
30 2023-06-12 19:23:00   SELL
33 2023-06-12 19:18:00   SELL
35 2023-06-12 19:16:00    BUY
36 2023-06-12 19:15:00   SELL
40 2023-06-12 19:09:00    BUY
44 2023-06-12 18:59:00   SELL
46 2023-06-12 18:54:00    BUY
47 2023-06-12 18:53:00   SELL
50 2023-06-12 18:50:00    BUY
60 2023-06-12 18:36:00   SELL
61 2023-06-12 18:35:00    BUY
63 2023-06-12 18:32:00   SELL
66 2023-06-12 18:27:00    BUY
69 2023-06-12 18:24:00   SELL
72 2023-06-12 18:18:00    BUY
76 2023-06-12 18:13:00   SELL
84 2023-06-12 17:57:00    BUY
86 2023-06-12 17:53:00   SELL
87 2023-06-12 17:51:00    BUY
88 2023-06-12 17:49:00   SELL
89 2023-06-12 17:48:00    BUY
92 2023-06-12 17:45:00   SELL